/* Copyright 2026 上海如静知华信息科技有限公司 */
package cn.zhuatech.meetingai;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class MeetingAiApiIntegrationTests {
    @Autowired MockMvc mvc; private String operatorToken; private String plannerToken;
    @BeforeEach void login()throws Exception{operatorToken=token("operator","Demo@2026");plannerToken=token("planner","Demo@2026");}
    private String token(String u,String p)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\""+p+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher matcher=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!matcher.find())throw new AssertionError("登录响应中缺少 token");return matcher.group(1);}
    @Test void operatorCanReadShopfloorDashboard()throws Exception{mvc.perform(get("/api/shopfloor/dashboard").header("Authorization","Bearer "+operatorToken)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)).andExpect(jsonPath("$.data.metrics[0].label").value("本月会议"));}
    @Test void plannerCanReadWorkRecords()throws Exception{mvc.perform(get("/api/admin/work-orders").header("Authorization","Bearer "+plannerToken)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(4));}
    @Test void operatorCanSubmitProductionReport()throws Exception{mvc.perform(post("/api/shopfloor/work-orders/1/reports").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"operationName\":\"治理评审\",\"goodQty\":2,\"defectQty\":1,\"remark\":\"证据完整\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.message").value("会议纪要反馈已提交")).andExpect(jsonPath("$.data.completedQty").value(18));}
    @Test void operatorCanAssessAiRisk()throws Exception{mvc.perform(post("/api/shopfloor/ai-risk-assessment").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"systemName\":\"授信助手\",\"useCase\":\"材料审阅\",\"autonomyLevel\":3,\"handlesPersonalData\":true,\"humanOversight\":false,\"externalImpact\":true,\"evaluated\":false,\"transparencyNotice\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.riskTier").value("HIGH")).andExpect(jsonPath("$.data.releaseDecision").value("BLOCK"));}
    @Test void operatorCanExtractMeetingActions()throws Exception{mvc.perform(post("/api/ai/meeting/analyze").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"meetingTitle\":\"产品评审会\",\"transcript\":\"周言负责在周五前完成原型。产品负责人确认发布范围。\",\"attendeeCount\":8,\"openDecisions\":1}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.actionItems.length()").value(2)).andExpect(jsonPath("$.data.riskFlags.length()").value(1));}
    @Test void anonymousRequestIsDenied()throws Exception{mvc.perform(get("/api/admin/dashboard")).andExpect(status().isForbidden());}
}
