/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.meetingai.service;
import cn.zhuatech.meetingai.common.BusinessException; import cn.zhuatech.meetingai.dto.MeetingAiDto.*; import cn.zhuatech.meetingai.model.*; import cn.zhuatech.meetingai.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class MeetingAiService {
    private final WorkRecordRepository orders; private final ActivityRecordRepository reports; private final ResourceRegisterRepository resources; private final ReviewRecordRepository reviewRecords; private final CurrentUserService current;
    public MeetingAiService(WorkRecordRepository orders,ActivityRecordRepository reports,ResourceRegisterRepository resources,ReviewRecordRepository reviewRecords,CurrentUserService current){this.orders=orders;this.reports=reports;this.resources=resources;this.reviewRecords=reviewRecords;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getOperatingUnitCode();List<WorkRecord> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByOperatingUnitCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<WorkRecordView> workRecords(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){WorkRecord order=orders.findById(id).orElseThrow(()->new BusinessException("会议任务不存在"));if(order.getStatus()==WorkRecord.Status.COMPLETED)throw new BusinessException("已归档任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成控制项不能超过待评审控制项");order.report(request.goodQty(),request.defectQty());reports.save(new ActivityRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getRecordNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<WorkRecord> list){int planned=list.stream().mapToInt(WorkRecord::getPlannedQty).sum(),done=list.stream().mapToInt(WorkRecord::getCompletedQty).sum(),defects=list.stream().mapToInt(WorkRecord::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("本月会议",String.format("%,d",planned),list.size()+" 个评审任务","blue"),new Metric("控制项完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("证据通过率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项缺口","warn"),new Metric("高风险待复核",resources.countByStatus(ResourceRegister.Status.ALARM)+"",reviewRecords.countByResult(ReviewRecord.Result.PENDING)+" 项待决策","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),resources.findAllByOrderByCodeAsc().stream().map(e->new ControlView(e.getCode(),e.getName(),e.getOperatingUnit().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),reviewRecords.findTop10ByOrderByIdDesc().stream().map(i->new ReviewRecordView(i.getReviewRecordNo(),i.getWorkRecord().getRecordNo(),i.getWorkRecord().getSubjectName(),i.getReviewRecordType(),i.getReviewRecordQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private WorkRecordView view(WorkRecord o){return new WorkRecordView(o.getId(),o.getRecordNo(),o.getSubjectCode(),o.getSubjectName(),o.getOperatingUnit().getName(),o.getOperatingUnit().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getVersionNo(),progress(o));}
    private int progress(WorkRecord o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
